

# This file was *autogenerated* from the file exercise-b.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_10 = Integer(10); _sage_const_2 = Integer(2)
import random

def return_tuple(k):

    def extended_gcd(p,q):
        if q == _sage_const_0 :
            return _sage_const_1 , _sage_const_0 
        else:
            x, y = extended_gcd(q, p % q)
            return y, x - (p // q) * y

    while True:
        p = random.randint(_sage_const_10 **(k-_sage_const_1 ), _sage_const_10 **k)
        if(p % _sage_const_2  == _sage_const_0 ):
            continue

        if is_prime(p):
            break

    while True:
        q = random.randint(_sage_const_10 **(k-_sage_const_1 ), _sage_const_10 **k)
        if(q % _sage_const_2  == _sage_const_0 ):
            continue

        if is_prime(q) and p != q:
            break

    a, b = extended_gcd(p,q)

    return (p,q,a,b)


k = int(input("Enter the value of k : "))
tup = return_tuple(k)
print("The tuple generated is", tup)

